name: Linux Kernel Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Kernel Source
      run: |
        curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.8.9.tar.xz
        tar -xvf linux-6.8.9.tar.xz
        cd linux-6.8.9 #change dir
        curl -LO "https://filebin.net/archive/48r3h1ip1ybi6407/zip"
        unzip zip
        mv _config .config

    - name: Install necessary dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential flex bison libssl-dev libncurses5-dev libncurses-dev  libelf-dev bc


    - name: Build Kernel
      run: |
        cd linux-6.8.9 #change dir
        make -j$(nproc)
        make modules -j$(nproc)

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-artifacts
        path: |
          linux-6.8.9
