name: Linux Kernel Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Kernel Source
      run: |
        curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.8.9.tar.xz
        tar -xvf linux-6.8.9.tar.xz
        cd linux-6.8.9 #change dir
        curl -LO "https://filebin.net/archive/48r3h1ip1ybi6407/zip"
        unzip zip
        mv _config .config

    - name: Install necessary dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential flex bison libssl-dev libncurses5-dev

    - name: Configure Kernel
      run: make defconfig

    - name: Build Kernel
      run: make -j$(nproc)

    - name: Test Kernel (optional)
      run: make test (replace with your kernel test command)
